unbind C-b
set -g prefix C-x

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g default-terminal "tmux-256color"

# No delay for escape key press
set -s escape-time 0

set -g mouse on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

set-window-option -g mode-keys vi

# Vim-style pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'


set -g @rose_pine_window_status_separator " | " # Changes the default icon that appears between window names
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar

set -g @rose_pine_disable_active_window_menu 'on'

#set -g @plugin 'Nybkox/tmux-kanagawa'
#set -g @kanagawa-show-powerline true
#set -g @kanagawa-show-flags true
#set -g @kanagawa-ignore-window-colors true

# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'
# tmux-continuum settings
set -g @continuum-restore 'off'

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Split panes using |
bind | split-window -h -c "#{pane_current_path}"

# New window with current path
bind c new-window -c "#{pane_current_path}"

# Resize panes with arrow keys
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Quick window selection
bind -r Tab last-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
