# Use zsh as default
set -g default-shell /bin/zsh

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g history-limit 1000000    # Increase history size (from 2,000)
set -g mouse on                 # Enable mouse support
set -g status-interval 2        # Update the status bar every 3 seconds (default: 15 seconds)
set -g allow-passthrough on   # Allow programs in the pane to bypass tmux (e.g. for image preview)

# Set prefix key
unbind C-b              # Unbind the default prefix key
set -g prefix C-Space   # Set new prefix key to Ctrl+Space

# Refresh tmux config with r
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'rose-pine/tmux'

# rose pine
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_window_status_separator " | " # Changes the default icon that appears between window names
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_disable_active_window_menu 'on'

#set -g @plugin 'Nybkox/tmux-kanagawa'
#set -g @kanagawa-show-powerline true
#set -g @kanagawa-show-flags true
#set -g @kanagawa-ignore-window-colors true

# Start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection 

bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Enable vi mode to allow us to use vim keys to move around in copy mode (Prefix + [ places us in copy mode)
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed

# Vim-style pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Use m key to maximize pane
bind -r m resize-pane -Z

# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'
#set -g @continuum-restore 'on'

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Split horizontally in CWD with \
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

# New window with current path
bind c new-window -c "#{pane_current_path}"

# Resize panes with arrow keys
bind -r H resize-pane -L 1
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Quick window selection
bind -r Tab last-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
