git:
  overrideGpg: true
gui:
  authorColors:
    "*": magenta
  showNumstatInFilesView: true
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - "#013e4a"
keybinding:
  files:
    viewResetOptions: <disabled>
