
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░

#flatpak
env XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/home/limon/.local/share/flatpak/exports/share:/usr/share

decoration {
  blur {
    enabled = true
    passes = 3
    size = 8
    vibrancy = 0.25
    ignore_opacity = false
    noise = 0.02
  }
}


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    #follow_mouse = 1
    sensitivity = 0
    force_no_accel = 1
    # accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
    }

}



# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for waybar transparency
layerrule= unset, waybar
layerrule= ignorezero, waybar
