#! /bin/sh

# Restore wallpaper
bash "$HOME/.config/bspwm/.fehbg" 

pgrep -x sxhkd > /dev/null || sxhkd &
"$HOME/.config/bspwm/polybar/launch.sh" &

bspc monitor HDMI2 -d 1 2 3 4

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config top_padding          0

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# Kill if already running
killall -9 picom sxhkd dunst

# Launch notification daemon
dunst -config "$HOME/.config/bspwm/dunstrc" &

# Launch keybindings daemon
sxhkd &

# start compositor
picom --config "$HOME/.config/bspwm/picom.conf" &

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/one-dark "$XFCE_TERM_PATH"/terminalrc


# workspace 1 (Internet Browser)
bspc rule -a firefox desktop='^1' follow=on focus=on

# workspace 2 (Text Editor)
bspc rule -a discord desktop='^2' follow=on focus=on

# workspace 3 (Files)
bspc rule -a nemo desktop='^3' follow=on focus=on 

# workspace 4 (Media)
bspc rule -a mpv desktop='^4' follow=on focus=on
