#!/bin/env bash

if [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
  CONFIG="$HOME/.config/alacritty/alacritty.yml"
fi

case "$1" in
  '-f')
          alacritty --class 'Alafloat,Alafloat' --config-file "$CONFIG"
          ;;
  '-m')
          alacritty --class 'Alamax,Alamax' --config-file "$CONFIG" -o window.startup_mode=fullscreen window.padding.x=30 window.padding.y=30
          ;;

  '-e')
          alacritty --config-file "$CONFIG" -e "$2"
          ;;
     *)
          alacritty --config-file "$CONFIG"
esac
