return {
  "akinsho/bufferline.nvim",
  lazy = true,
  event = { "BufReadPost", "BufNewFile" },
  dependencies = {
    "nvim-tree/nvim-web-devicons",
  },
  config = function()
    require("bufferline").setup {
      options = {
        mode = "buffers",
        themable = false,
        numbers = "none",
        close_command = function(n) Snacks.bufdelete(n) end,
        right_mouse_command = function(n) Snacks.bufdelete(n) end,
        left_mouse_command = "buffer %d",
        buffer_close_icon = "󰅖",
        close_icon = "",
        path_components = 1,
        modified_icon = "●",
        left_trunc_marker = "",
        right_trunc_marker = "",
        max_name_length = 30,
        tab_size = 20,
        diagnostics = false,
        color_icons = true,
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = true,
        separator_style = { "│", "│" },
        enforce_regular_tabs = true,
        always_show_bufferline = false,
        show_tab_indicators = false,
        indicator = { style = "none" },
        minimum_padding = 1,
        maximum_padding = 5,
        sort_by = "insert_at_end",
      },
      highlights = {
        fill = { bg = "NONE" },
        background = { bg = "NONE", fg = "NONE" },
        separator = { fg = "NONE", bg = "NONE" },
        buffer_selected = {
          bg = "NONE",
          bold = true,
          italic = false,
          fg = "NONE",
        },
        close_button = { bg = "NONE" },
        close_button_selected = { bg = "NONE" },
        tab_selected = { bg = "NONE" },
        indicator_selected = { bg = "NONE" },
        offset_separator = { fg = "NONE", bg = "NONE" },
        modified = { bg = "NONE" },
        modified_selected = { bg = "NONE" },
        -- Truncation markers styling
        trunc_marker = { bg = "NONE", fg = "NONE" },
      },
    }
  end,
}
