return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "VeryLazy",
  main = "nvim-treesitter.configs",
  dependencies = {
    {
      "windwp/nvim-ts-autotag",
      ft = { "html", "typescript", "typescriptreact", "tsx", "vue", "svelte" },
      config = function()
        require("nvim-ts-autotag").setup()
      end,
    },
  },
  opts = {
    ensure_installed = {
      "json",
      "jsonc",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "html",
      "css",
      "prisma",
      "markdown",
      "markdown_inline",
      "svelte",
      "graphql",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "query",
      "vimdoc",
      "c",
      "cpp",
      "regex",
      "go",
      "python",
      "rust",
      "toml",
      "http",
    },
    auto_install = true,
    highlight = { enable = true, additional_vim_regex_highlighting = { "ruby" } },
    indent = { enable = true, disable = { "ruby" } },
  },
}
