return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "VeryLazy",
  main = "nvim-treesitter.configs",
  dependencies = {
    {
      "windwp/nvim-ts-autotag",
      ft = { "html", "typescript", "typescriptreact", "tsx", "vue", "svelte" },
      config = function()
        require("nvim-ts-autotag").setup()
      end,
    },
  },
  opts = {
    ensure_installed = {
      "c",
      "markdown",
      "markdown_inline",
      "vim",
      "make",
      "vimdoc",
      "query",
      "bash",
      "diff",
      "comment",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "javascript",
      "typescript",
      "tsx",
      "jsdoc",
      "yaml",
      "toml",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "ssh_config",
      "go",
      "gosum",
      "gotmpl",
      "gomod",
      "gowork",
      "rust",
      "sql",
      "zig",
      "vue",
      "ziggy",
      "ziggy_schema",
      "kdl",
      "python",
      "html",
      "css",
      "cpp",
      "just",
      "nix",
      "dockerfile",
      "svelte",
      "nginx",
      "php",
    },
    auto_install = true,
    highlight = { enable = true, additional_vim_regex_highlighting = { "ruby" } },
    indent = { enable = true, disable = { "ruby" } },
  },
}
